// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1le_IUxqc57Z4RIekPJoCZAbyKCiEMMY',
    appId: '1:946524886850:web:5a0478944bf2b0fb945adb',
    messagingSenderId: '946524886850',
    projectId: 'ecommerceorange-7017c',
    authDomain: 'ecommerceorange-7017c.firebaseapp.com',
    storageBucket: 'ecommerceorange-7017c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGavUOBYxD10K97UpFdsFW--VNmZV6f0A',
    appId: '1:946524886850:android:ac68ffd1e5dc6a92945adb',
    messagingSenderId: '946524886850',
    projectId: 'ecommerceorange-7017c',
    storageBucket: 'ecommerceorange-7017c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqKHq_Nw9RCYIBQU2I-7YY-T457GtfZd0',
    appId: '1:946524886850:ios:ccf57b0a248d2828945adb',
    messagingSenderId: '946524886850',
    projectId: 'ecommerceorange-7017c',
    storageBucket: 'ecommerceorange-7017c.appspot.com',
    iosBundleId: 'com.example.ecommerceorange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqKHq_Nw9RCYIBQU2I-7YY-T457GtfZd0',
    appId: '1:946524886850:ios:c8464301dc6807dd945adb',
    messagingSenderId: '946524886850',
    projectId: 'ecommerceorange-7017c',
    storageBucket: 'ecommerceorange-7017c.appspot.com',
    iosBundleId: 'com.example.ecommerceorange.RunnerTests',
  );
}
